### PR TITLE
streaming application support to repoze.zodbconn.connector middleware

### PR DESCRIPTION
**Pull request by harobed**
This patch append streaming application support to repoze.zodbconn.connector middleware

This patch is related to https://github.com/repoze/repoze.zodbconn/issues/1 issue

Regards,
Stephane

### CODE REVIEW

**Comment by tseaver** [comment]
The main part of the patch looks fine (the change to repoze/zodbconn/connector.py).  However, I don't want to pull either of the other two bits
- The maintainers don't like the DRY violation of MANIFEST.in, preferring to use setuptools_git to ensure that all VCS-managed files are included in a release.
- Tagging builds is just the Wrong Thing (TM).

**Comment by harobed** [comment]
Ok, I'll fix this task.

**Comment by harobed** [comment]
>   The maintainers don't like the DRY violation of MANIFEST.in, preferring to use setuptools_git to ensure that all VCS-managed files are included in a release.

Ok, that is done here :
https://github.com/harobed/repoze.zodbconn/commit/86a2ffb2db0bc5d80d15e5767ccde927e55cca7c

>    Tagging builds is just the Wrong Thing (TM).

It's done : https://github.com/harobed/repoze.zodbconn/commit/61aa461605815eb8a9cd0f4e69ba7baaefaac5ab

Now I think you can merge.

Regards,
Stephane

**Comment by tseaver** [comment]
Great, thanks very much.  One more thing:  could you please "sign" CONTRIBUTORS.txt by adding your name and the date to the bottom?

**Comment by harobed** [comment]
> One more thing: could you please "sign" CONTRIBUTORS.txt by adding your name and the date to the bottom?

Ok, it's done.

Regards,
Stephane

**Pull request merged**
